@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" DistinctPersonList
AddressBook *-right-> "1" DistinctClubList
AddressBook *-right-> "1" DistinctMembershipList
AddressBook *-right-> "1" DistinctTagList
DistinctTagList -[hidden]down- DistinctPersonList
DistinctTagList -[hidden]down- DistinctPersonList

DistinctTagList -right-> "*" Tag
DistinctPersonList -right-> Person
DistinctClubList -right-> Club
DistinctMembershipList -right-> Membership

Person -up-> "*" Tag

Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address

Club -up-> "*" Tag

Club *--> Name
Club *--> Phone
Club *--> Email
Club *--> Address

Membership *--> Person
Membership *--> Club
@enduml
